### PR TITLE
Fix to handle empty departure time from MTA api

### PR DESCRIPTION
**Pull request by wilsonchaney**
A basic fix to handle the case described in https://github.com/nolanbconaway/underground/issues/23.

This will effectively drop the malformed `stop_time_update` element.

### CODE REVIEW

**Review by nolanbconaway — CHANGES_REQUESTED** [review]
Heck yeah! thanks for tracking this down.

Only big note is that you'll need to bump the library version in https://github.com/nolanbconaway/underground/blob/master/src/underground/version, else this never makes it to pypi.

I would also feel safer in my heart if you added your [sample data](https://gist.github.com/wilsonchaney/09b87a44206992a978bced1892ac24e3) in a test. That test would ultimately prove that these changes solve the target issue. Are you up for adding the test?

**Comment by nolanbconaway** [comment]
the dependencies for this were a mess so i fixed them in https://github.com/nolanbconaway/underground/pull/25

you'll need to merge in the changes here!

**Comment by wilsonchaney** [comment]
No problem!

I went ahead and merged your changes, bumped the version to `0.3.2` and added a basic test. Let me know if you'd prefer more coverage. (I didn't use the literal data from the gist, just a stripped down version for the test)

**Review by nolanbconaway — APPROVED** [review]

**Comment by nolanbconaway** [comment]
Will handle the black stuff myself. Thanks for the work!

**Comment by nolanbconaway** [comment]
@wilsonchaney enjoy 0.3.2! https://github.com/nolanbconaway/underground/releases/tag/v0.3.2

**Pull request merged**
